//go:build !ignore_autogenerated

/*
Copyright 2026 The k-deskflight Authors.

Licensed under the MIT License (see LICENSE at the repository root).

This file is generated by controller-gen. Do not edit by hand —
re-run `make manifests` (slice-M2 §2.3) and commit the result.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerCheckSpec) DeepCopyInto(out *CertManagerCheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerCheckSpec.
func (in *CertManagerCheckSpec) DeepCopy() *CertManagerCheckSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChecksSpec) DeepCopyInto(out *ChecksSpec) {
	*out = *in
	if in.KubernetesVersion != nil {
		in, out := &in.KubernetesVersion, &out.KubernetesVersion
		*out = new(KubernetesVersionCheckSpec)
		**out = **in
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(StorageClassCheckSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.IngressClass != nil {
		in, out := &in.IngressClass, &out.IngressClass
		*out = new(IngressClassCheckSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(CertManagerCheckSpec)
		**out = **in
	}
	if in.ClusterResources != nil {
		in, out := &in.ClusterResources, &out.ClusterResources
		*out = new(ClusterResourcesCheckSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChecksSpec.
func (in *ChecksSpec) DeepCopy() *ChecksSpec {
	if in == nil {
		return nil
	}
	out := new(ChecksSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterResourcesCheckSpec) DeepCopyInto(out *ClusterResourcesCheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterResourcesCheckSpec.
func (in *ClusterResourcesCheckSpec) DeepCopy() *ClusterResourcesCheckSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterResourcesCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressClassCheckSpec) DeepCopyInto(out *IngressClassCheckSpec) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressClassCheckSpec.
func (in *IngressClassCheckSpec) DeepCopy() *IngressClassCheckSpec {
	if in == nil {
		return nil
	}
	out := new(IngressClassCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesVersionCheckSpec) DeepCopyInto(out *KubernetesVersionCheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesVersionCheckSpec.
func (in *KubernetesVersionCheckSpec) DeepCopy() *KubernetesVersionCheckSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesVersionCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenDeskPreflightCheck) DeepCopyInto(out *OpenDeskPreflightCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenDeskPreflightCheck.
func (in *OpenDeskPreflightCheck) DeepCopy() *OpenDeskPreflightCheck {
	if in == nil {
		return nil
	}
	out := new(OpenDeskPreflightCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenDeskPreflightCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenDeskPreflightCheckList) DeepCopyInto(out *OpenDeskPreflightCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenDeskPreflightCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenDeskPreflightCheckList.
func (in *OpenDeskPreflightCheckList) DeepCopy() *OpenDeskPreflightCheckList {
	if in == nil {
		return nil
	}
	out := new(OpenDeskPreflightCheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenDeskPreflightCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenDeskPreflightCheckSpec) DeepCopyInto(out *OpenDeskPreflightCheckSpec) {
	*out = *in
	in.Checks.DeepCopyInto(&out.Checks)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenDeskPreflightCheckSpec.
func (in *OpenDeskPreflightCheckSpec) DeepCopy() *OpenDeskPreflightCheckSpec {
	if in == nil {
		return nil
	}
	out := new(OpenDeskPreflightCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenDeskPreflightCheckStatus) DeepCopyInto(out *OpenDeskPreflightCheckStatus) {
	*out = *in
	in.Summary.DeepCopyInto(&out.Summary)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenDeskPreflightCheckStatus.
func (in *OpenDeskPreflightCheckStatus) DeepCopy() *OpenDeskPreflightCheckStatus {
	if in == nil {
		return nil
	}
	out := new(OpenDeskPreflightCheckStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClassCheckSpec) DeepCopyInto(out *StorageClassCheckSpec) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassCheckSpec.
func (in *StorageClassCheckSpec) DeepCopy() *StorageClassCheckSpec {
	if in == nil {
		return nil
	}
	out := new(StorageClassCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Summary) DeepCopyInto(out *Summary) {
	*out = *in
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Summary.
func (in *Summary) DeepCopy() *Summary {
	if in == nil {
		return nil
	}
	out := new(Summary)
	in.DeepCopyInto(out)
	return out
}
