#!/usr/bin/env bash
# Renders .security/.trivyignore.in -> .security/.trivyignore.
#
# Requires GNU coreutils (date -d). Default on Linux/CI; macOS
# maintainers need `gdate` or a GNU-coreutils overlay.
#
# Slice-M7 §2.4 and ADR 0012 §2.8/§2.9 require every Trivy ignore
# entry to carry an `expires:YYYY-MM-DD` comment. This script
# enforces the contract:
#
#   - `.trivyignore.in` is the committed source-of-truth (each entry
#     on its own line, with an inline `# expires:YYYY-MM-DD` plus
#     optional `reason:` comment).
#   - `.trivyignore` is the generated Trivy-readable artifact
#     (gitignored — see `.gitignore`).
#   - An entry whose `expires` lies in the past breaks the renderer
#     with a non-zero exit; this propagates through `make image-scan`
#     into `make security-gates` and forces a maintenance commit.
#   - An entry without an `expires:` comment also breaks the
#     renderer — the comment is mandatory.
#
# Usage:
#   bash scripts/render-trivyignore.sh
#
# Output:
#   .security/.trivyignore (overwrites; deleted on error).

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE="${ROOT_DIR}/.security/.trivyignore.in"
TARGET="${ROOT_DIR}/.security/.trivyignore"
TARGET_TMP="${TARGET}.$$.tmp"

trap 'rm -f "${TARGET_TMP}"' EXIT

if [[ ! -f "${SOURCE}" ]]; then
    echo "render-trivyignore: ${SOURCE} not found" >&2
    exit 1
fi

today_epoch="$(date -u +%s)"
had_error=0
entry_count=0

{
    echo "# Generated by scripts/render-trivyignore.sh from .security/.trivyignore.in"
    echo "# DO NOT EDIT — change .trivyignore.in and re-run \`make image-scan\`."
    echo "#"
    echo "# Format: one CVE/GHSA ID per line, preceded by an audit comment."
    echo ""
} > "${TARGET_TMP}"

line_num=0
while IFS= read -r line || [[ -n "${line}" ]]; do
    line_num=$((line_num + 1))

    # Trim leading + trailing whitespace.
    trimmed="${line#"${line%%[![:space:]]*}"}"
    trimmed="${trimmed%"${trimmed##*[![:space:]]}"}"

    # Skip blank lines and pure-comment lines.
    if [[ -z "${trimmed}" ]] || [[ "${trimmed:0:1}" == "#" ]]; then
        continue
    fi

    # Extract the leading token as the identifier.
    id="${trimmed%%[[:space:]]*}"

    # Validate identifier shape.
    if ! [[ "${id}" =~ ^(CVE|GHSA)- ]]; then
        echo "render-trivyignore: ${SOURCE}:${line_num}: invalid identifier '${id}' (expected CVE-… or GHSA-…)" >&2
        had_error=1
        continue
    fi

    # Pull the inline `expires:YYYY-MM-DD` substring.
    expires=""
    if [[ "${trimmed}" =~ expires:([0-9]{4}-[0-9]{2}-[0-9]{2}) ]]; then
        expires="${BASH_REMATCH[1]}"
    fi
    if [[ -z "${expires}" ]]; then
        echo "render-trivyignore: ${SOURCE}:${line_num}: ${id} missing 'expires:YYYY-MM-DD' comment" >&2
        had_error=1
        continue
    fi

    # Validate that the expires date parses and lies in the future.
    exp_epoch="$(date -u -d "${expires}" +%s 2>/dev/null || true)"
    if [[ -z "${exp_epoch}" ]]; then
        echo "render-trivyignore: ${SOURCE}:${line_num}: ${id} unparseable expires date '${expires}'" >&2
        had_error=1
        continue
    fi
    if (( exp_epoch < today_epoch )); then
        echo "render-trivyignore: ${SOURCE}:${line_num}: ${id} expired (${expires}) — renew or remove the entry" >&2
        had_error=1
        continue
    fi

    # Optional `reason: …` substring (until next `#` or EOL).
    reason=""
    if [[ "${trimmed}" =~ reason:[[:space:]]*([^#]*) ]]; then
        reason="${BASH_REMATCH[1]}"
        # Trim trailing whitespace.
        reason="${reason%"${reason##*[![:space:]]}"}"
    fi

    if [[ -n "${reason}" ]]; then
        echo "# ${id} — expires:${expires} — reason: ${reason}" >> "${TARGET_TMP}"
    else
        echo "# ${id} — expires:${expires}" >> "${TARGET_TMP}"
    fi
    echo "${id}" >> "${TARGET_TMP}"
    entry_count=$((entry_count + 1))
done < "${SOURCE}"

if (( had_error )); then
    # Remove any stale .trivyignore so that a subsequent `make
    # image-scan` cannot silently reuse the previous render — the
    # header comment in this script promises "deleted on error", and
    # a stale ignore-file would mask the configuration drift the
    # renderer just refused to encode.
    rm -f "${TARGET}"
    echo "render-trivyignore: errors found — no .trivyignore written" >&2
    exit 1
fi

mv "${TARGET_TMP}" "${TARGET}"
if (( entry_count == 1 )); then
    echo "render-trivyignore: wrote ${TARGET} (1 entry)"
else
    echo "render-trivyignore: wrote ${TARGET} (${entry_count} entries)"
fi
